services:
  assistant-backend:
    image: blueman2903/lola-backend:${TAG:-latest}
    container_name: assistant-backend
    restart: always
    env_file:
      - ${ENV_FILE_PATH:-.env}
    volumes:
      - lola_session_data:/home/appuser/data

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/Lola/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/Lola/frontend:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - assistant-backend

volumes:
  lola_session_data:
  caddy_data:
  caddy_config: